// clang-format off
// MUST BE at the beginning before any other <cmath> include (e.g. in armadillo's headers)
#define _USE_MATH_DEFINES // required for Visual Studio
#include <cmath>
// clang-format on

#include <string>
#include <vector>

#include "libKriging/Kriging.hpp"

#define CATCH_CONFIG_MAIN
#include <catch2/catch.hpp>

namespace {

const std::vector<std::string> differentiable_kernels = {"gauss", "matern3_2", "matern5_2"};

// Smooth 2-d test function and its analytical gradient.
double f(const arma::rowvec& x) {
  return std::sin(2 * x[0]) + 0.5 * x[1] * x[1] + 0.3 * x[0] * x[1];
}
arma::rowvec df(const arma::rowvec& x) {
  return arma::rowvec{2 * std::cos(2 * x[0]) + 0.3 * x[1], x[1] + 0.3 * x[0]};
}

struct Design {
  arma::mat X;
  arma::vec y;
  arma::mat dy;
};

Design make_design(arma::uword n, unsigned int seed) {
  arma::arma_rng::set_seed(seed);
  Design D;
  D.X = arma::randu<arma::mat>(n, 2);
  D.y.set_size(n);
  D.dy.set_size(n, 2);
  for (arma::uword a = 0; a < n; a++) {
    D.y[a] = f(D.X.row(a));
    D.dy.row(a) = df(D.X.row(a));
  }
  return D;
}

}  // namespace

TEST_CASE("Kriging::fit(...,grady=) interpolates values and gradients", "[Kriging][grad]") {
  Design D = make_design(12, 71);

  for (const auto& kernel : differentiable_kernels) {
    Kriging k(kernel);
    k.fit(D.y, D.X, Trend::RegressionModel::Constant, false, "none", "LL", []() {
      Kriging::Parameters p;
      p.theta = arma::mat{{0.7, 0.7}};
      p.is_theta_estim = false;
      return p;
    }(), D.dy);

    auto [mean, stdev, cov, mean_deriv, stdev_deriv] = k.predict(D.X, true, false, true);

    INFO("kernel=" << kernel);
    for (arma::uword a = 0; a < D.X.n_rows; a++) {
      // Values are interpolated ...
      REQUIRE(mean[a] == Approx(D.y[a]).margin(1e-6));
      REQUIRE(stdev[a] == Approx(0.0).margin(1e-4));
      // ... and so are the gradients, which a value-only fit cannot achieve.
      for (arma::uword j = 0; j < 2; j++)
        REQUIRE(mean_deriv(a, j) == Approx(D.dy(a, j)).margin(1e-4));
    }
  }
}

TEST_CASE("Kriging direct constructor accepts grady", "[Kriging][grad]") {
  Design D = make_design(12, 71);

  Kriging::Parameters p;
  p.theta = arma::mat{{0.7, 0.7}};
  p.is_theta_estim = false;

  Kriging k(D.y, D.X, "gauss", Trend::RegressionModel::Constant, false, "none", "LL", p, D.dy);

  auto [mean, stdev, cov, mean_deriv, stdev_deriv] = k.predict(D.X, true, false, true);
  for (arma::uword a = 0; a < D.X.n_rows; a++) {
    REQUIRE(mean[a] == Approx(D.y[a]).margin(1e-6));
    for (arma::uword j = 0; j < 2; j++)
      REQUIRE(mean_deriv(a, j) == Approx(D.dy(a, j)).margin(1e-4));
  }
}

TEST_CASE("Kriging::fit(...,grady=) beats a value-only fit out of sample", "[Kriging][grad]") {
  Design D = make_design(10, 72);

  arma::arma_rng::set_seed(720);
  arma::mat X_test = arma::randu<arma::mat>(200, 2);
  arma::vec y_test(X_test.n_rows);
  for (arma::uword a = 0; a < X_test.n_rows; a++)
    y_test[a] = f(X_test.row(a));

  for (const auto& kernel : differentiable_kernels) {
    Kriging k_plain(kernel);
    k_plain.fit(D.y, D.X, Trend::RegressionModel::Constant, false, "BFGS", "LL");

    Kriging k_grad(kernel);
    k_grad.fit(D.y, D.X, Trend::RegressionModel::Constant, false, "BFGS", "LL", {}, D.dy);

    auto [mean_plain, s1, c1, d1, e1] = k_plain.predict(X_test, false, false, false);
    auto [mean_grad, s2, c2, d2, e2] = k_grad.predict(X_test, false, false, false);

    double rmse_plain = std::sqrt(arma::mean(arma::square(mean_plain - y_test)));
    double rmse_grad = std::sqrt(arma::mean(arma::square(mean_grad - y_test)));

    INFO("kernel=" << kernel << " rmse_plain=" << rmse_plain << " rmse_grad=" << rmse_grad);
    REQUIRE(rmse_grad < rmse_plain);
  }
}

TEST_CASE("Kriging::fit(...,grady=) recovers an exactly representable trend", "[Kriging][grad]") {
  // With a linear trend and data generated by that exact trend, the GP part
  // must vanish: predictions and their gradients are exact everywhere.
  const arma::uword n = 8;
  arma::arma_rng::set_seed(73);
  arma::mat X = arma::randu<arma::mat>(n, 2);
  const arma::rowvec slope = {1.5, -0.8};
  const double intercept = 0.25;

  arma::vec y(n);
  arma::mat dy(n, 2);
  for (arma::uword a = 0; a < n; a++) {
    y[a] = intercept + arma::dot(X.row(a), slope);
    dy.row(a) = slope;
  }

  Kriging k("gauss");
  k.fit(y, X, Trend::RegressionModel::Linear, false, "none", "LL", []() {
    Kriging::Parameters p;
    p.theta = arma::mat{{0.5, 0.5}};
    p.is_theta_estim = false;
    return p;
  }(), dy);

  arma::arma_rng::set_seed(730);
  arma::mat X_test = arma::randu<arma::mat>(30, 2);
  auto [mean, stdev, cov, mean_deriv, stdev_deriv] = k.predict(X_test, false, false, true);

  for (arma::uword a = 0; a < X_test.n_rows; a++) {
    REQUIRE(mean[a] == Approx(intercept + arma::dot(X_test.row(a), slope)).margin(1e-6));
    for (arma::uword j = 0; j < 2; j++)
      REQUIRE(mean_deriv(a, j) == Approx(slope[j]).margin(1e-6));
  }
}

TEST_CASE("Kriging::fit(...,grady=) works with normalization", "[Kriging][grad]") {
  // Normalization rescales gradients by scaleX_j / scaleY; check the round trip
  // on data whose x and y ranges are far from unit scale.
  const arma::uword n = 10;
  arma::arma_rng::set_seed(74);
  arma::mat X = 100 * arma::randu<arma::mat>(n, 2) - 50;

  arma::vec y(n);
  arma::mat dy(n, 2);
  for (arma::uword a = 0; a < n; a++) {
    y[a] = 1000 * (0.01 * X(a, 0) * X(a, 0) - 0.02 * X(a, 1));
    dy(a, 0) = 1000 * 0.02 * X(a, 0);
    dy(a, 1) = -1000 * 0.02;
  }

  Kriging k("matern5_2");
  k.fit(y, X, Trend::RegressionModel::Constant, true, "none", "LL", []() {
    Kriging::Parameters p;
    p.theta = arma::mat{{0.6, 0.6}};
    p.is_theta_estim = false;
    return p;
  }(), dy);

  auto [mean, stdev, cov, mean_deriv, stdev_deriv] = k.predict(X, false, false, true);
  for (arma::uword a = 0; a < n; a++) {
    REQUIRE(mean[a] == Approx(y[a]).margin(1e-3 * std::max(1.0, std::abs(y[a]))));
    for (arma::uword j = 0; j < 2; j++)
      REQUIRE(mean_deriv(a, j) == Approx(dy(a, j)).margin(1e-2 * std::max(1.0, std::abs(dy(a, j)))));
  }
}

TEST_CASE("Kriging::fit(...,grady=) estimates theta by maximum likelihood", "[Kriging][grad]") {
  // The finite-difference gradient path must let BFGS actually improve the
  // likelihood compared to the starting point.
  Design D = make_design(10, 75);

  Kriging k("gauss");
  k.fit(D.y, D.X, Trend::RegressionModel::Constant, false, "BFGS", "LL", {}, D.dy);

  REQUIRE(k.is_theta_estim());
  REQUIRE(k.theta().n_elem == 2);
  REQUIRE(arma::all(k.theta() > 0));
  REQUIRE(k.sigma2() > 0);

  auto [ll_fit, g1] = k.logLikelihoodFun(k.theta(), false, false);
  auto [ll_other, g2] = k.logLikelihoodFun(arma::vec{5.0, 5.0}, false, false);
  REQUIRE(ll_fit > ll_other);
}

TEST_CASE("Kriging::fit(...,grady=) likelihood gradient matches finite differences", "[Kriging][grad]") {
  Design D = make_design(8, 76);

  Kriging k("matern5_2");
  k.fit(D.y, D.X, Trend::RegressionModel::Constant, false, "none", "LL", []() {
    Kriging::Parameters p;
    p.theta = arma::mat{{0.8, 0.6}};
    p.is_theta_estim = false;
    return p;
  }(), D.dy);

  arma::vec theta = {0.8, 0.6};
  auto [ll, grad] = k.logLikelihoodFun(theta, true, false);
  REQUIRE(grad.n_elem == 2);

  const double h = 1e-5;
  for (arma::uword j = 0; j < 2; j++) {
    arma::vec tp = theta, tm = theta;
    tp[j] += h;
    tm[j] -= h;
    double fd = (std::get<0>(k.logLikelihoodFun(tp, false, false)) - std::get<0>(k.logLikelihoodFun(tm, false, false)))
                / (2 * h);
    REQUIRE(grad[j] == Approx(fd).margin(1e-3 * std::max(1.0, std::abs(fd))));
  }
}

TEST_CASE("Kriging::fit(...,grady=) rejects unsupported settings", "[Kriging][grad]") {
  Design D = make_design(6, 77);

  // Kernels that are not mean-square differentiable.
  for (const auto& kernel : {"exp", "whitenoise"}) {
    Kriging k(kernel);
    INFO("kernel=" << kernel);
    REQUIRE_THROWS_AS(
        k.fit(D.y, D.X, Trend::RegressionModel::Constant, false, "BFGS", "LL", {}, D.dy), std::runtime_error);
  }

  // Mis-shaped gradient matrix.
  {
    Kriging k("gauss");
    REQUIRE_THROWS_AS(
        k.fit(D.y, D.X, Trend::RegressionModel::Constant, false, "BFGS", "LL", {}, D.dy.head_rows(3)),
        std::runtime_error);
    REQUIRE_THROWS_AS(
        k.fit(D.y, D.X, Trend::RegressionModel::Constant, false, "BFGS", "LL", {}, D.dy.head_cols(1)),
        std::runtime_error);
  }

  // Objectives that are not defined on the augmented system.
  for (const auto& objective : {"LOO", "LMP", "VLL"}) {
    Kriging k("gauss");
    INFO("objective=" << objective);
    REQUIRE_THROWS_AS(
        k.fit(D.y, D.X, Trend::RegressionModel::Constant, false, "BFGS", objective, {}, D.dy), std::runtime_error);
  }
}

TEST_CASE("Kriging gradient observations block unsupported operations", "[Kriging][grad]") {
  Design D = make_design(6, 78);

  Kriging k("gauss");
  k.fit(D.y, D.X, Trend::RegressionModel::Constant, false, "none", "LL", []() {
    Kriging::Parameters p;
    p.theta = arma::mat{{0.7, 0.7}};
    p.is_theta_estim = false;
    return p;
  }(), D.dy);

  REQUIRE(!k.dy().is_empty());
  REQUIRE_THROWS_AS(k.simulate(2, 1, D.X), std::runtime_error);
  REQUIRE_THROWS_AS(k.update(D.y.head(2), D.X.head_rows(2), false), std::runtime_error);
}

TEST_CASE("Kriging::fit clears gradient observations from a previous fit", "[Kriging][grad]") {
  Design D = make_design(8, 79);

  Kriging k("gauss");
  k.fit(D.y, D.X, Trend::RegressionModel::Constant, false, "none", "LL", []() {
    Kriging::Parameters p;
    p.theta = arma::mat{{0.7, 0.7}};
    p.is_theta_estim = false;
    return p;
  }(), D.dy);
  REQUIRE(!k.dy().is_empty());

  // Re-fitting on values only must fall back to the plain model, not silently
  // keep the stale gradients.
  k.fit(D.y, D.X, Trend::RegressionModel::Constant, false, "none", "LL", []() {
    Kriging::Parameters p;
    p.theta = arma::mat{{0.7, 0.7}};
    p.is_theta_estim = false;
    return p;
  }());
  REQUIRE(k.dy().is_empty());

  Kriging k_ref("gauss");
  k_ref.fit(D.y, D.X, Trend::RegressionModel::Constant, false, "none", "LL", []() {
    Kriging::Parameters p;
    p.theta = arma::mat{{0.7, 0.7}};
    p.is_theta_estim = false;
    return p;
  }());

  auto [m1, s1, c1, d1, e1] = k.predict(D.X, true, false, false);
  auto [m2, s2, c2, d2, e2] = k_ref.predict(D.X, true, false, false);
  REQUIRE(arma::approx_equal(m1, m2, "absdiff", 1e-12));
  REQUIRE(arma::approx_equal(s1, s2, "absdiff", 1e-12));

  // ... and the operations blocked above are available again.
  REQUIRE_NOTHROW(k.simulate(2, 1, D.X));
}

TEST_CASE("Kriging::fit(...,grady=) with a nugget", "[Kriging][grad]") {
  // The nugget must apply to the value diagonal only: values are smoothed,
  // gradients are still matched closely.
  Design D = make_design(10, 80);

  Kriging k("gauss", Kriging::NoiseModel::Nugget);
  k.fit(D.y, D.X, Trend::RegressionModel::Constant, false, "BFGS", "LL", {}, D.dy);

  REQUIRE(k.nugget() >= 0);
  REQUIRE(k.sigma2() > 0);

  auto [mean, stdev, cov, mean_deriv, stdev_deriv] = k.predict(D.X, true, false, true);
  for (arma::uword a = 0; a < D.X.n_rows; a++) {
    REQUIRE(mean[a] == Approx(D.y[a]).margin(1e-2));
    for (arma::uword j = 0; j < 2; j++)
      REQUIRE(mean_deriv(a, j) == Approx(D.dy(a, j)).margin(1e-1));
  }
}
