---
title: "RLibKriging vs. DiceKriging"
subtitle: "Features & results comparisons"
author: "Yann Richet"
date: "2022"
---

This notebook is dedicated to RLibKriging coverage of DiceKriging features.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error=FALSE)
```

# Testing objectives

## 1D obj. function

```{r}
f_1D = function(x) 1-1/2*(sin(12*x)/(1+x)+2*cos(7*x)*x^5+0.7)
n_1D <- 5
set.seed(123)
X_1D <- cbind(runif(n_1D))
y_1D <- f_1D(X_1D)
```

## 2D obj. function

## ND obj. function

## Features matrix

```{r}
features=list(
    objective_function=c("1D", "2D", "ND"),
    kernel=c("gauss","exp","matern3_2","matern5_2","powexp", function(x,y){0.5*exp(-((x-y)/0.15)^2)+0.5*exp(-((1-x-y)/0.15)^2)}),
    trend=c("~1","~."),
    fit.objective=c("MLE","LOO"),
    fit.optim=c("BFGS","gen"),
    nugget=c(0, .001, "estim"),
    noise.var=c(0,.001),
    iso=c(TRUE, FALSE),
    knots=c(0,1,2)
    )
```


# Tests

```{r}
library(DiceKriging)
packageDescription("DiceKriging")
library(rlibkriging)
packageDescription("rlibkriging")
```

## Constructor

```{r}
for (objective_function in features$objective_function)
    for(kernel in features$kernel)
        for (trend in features$trend)
            for (fit.objective in features$fit.objective)
            for (fit.optim in features$fit.optim)
                for (nugget in features$nugget)
                    for (noise in features$noise) {
                        X = eval(parse(paste0("X_",objective_function)))
                        y = eval(parse(paste0("y_",objective_function)))
                        
                        m_DiceKriging = NULL
                        try(m_DiceKriging <- km(design=X, response=y, covtype = if (is.character(kernel)) kernel else NULL, formula=as.formula(trend), estim.method=fit.objective, nugget = nugget, nugget.estim = (nugget=="estim"), optim.method = fit.optim,  parinit = rep(.15,d), noise.var = noise, iso = iso, scaling = (knots!=0), knots=knots, kernel = if (is.function(kernel)) kernel else NULL, control = list(trace=F)))
                        constructor.DiceKriging[[paste(sep=",",objective_function,kernel,trend,fit.objective,fit.optim,nugget,)]]

                        
                        m_Kriging = NULL
                        try(m_Kriging <- Kriging(X=X, y=y, kernel = kernel, regmodel = as.formula(trend), normalize = FALSE, optim = "BFGS", objective=fit.objective, optim=fit.optim , parameters = list(theta=rep(.15,d))))

                        m_asDiceKriging = NULL
                        try(m_asDiceKriging <- as_km(design=X, response=y, covtype = if (is.character(kernel)) kernel else NULL, formula=as.formula(trend), estim.method=fit.objective, nugget = nugget, nugget.estim = (nugget=="estim"), optim.method = fit.optim,  parinit = rep(.15,d), kernel = if (is.function(kernel)) kernel else NULL, control = list(trace=F)))


}
```



# Summary of features matrix

