#ifndef LIBKRIGING_SRC_LIB_INCLUDE_LIBKRIGING_UTILS_LK_ARMADILLO_HPP
#define LIBKRIGING_SRC_LIB_INCLUDE_LIBKRIGING_UTILS_LK_ARMADILLO_HPP

#include "lkalloc.hpp"

#include <armadillo>

#endif  // LIBKRIGING_SRC_LIB_INCLUDE_LIBKRIGING_UTILS_LK_ARMADILLO_HPP
