//
// Created by Pascal Havé on 27/06/2020.
//

#ifndef LIBKRIGING_BINDINGS_PYTHON_SRC_LINEARREGRESSION_BINDING_HPP
#define LIBKRIGING_BINDINGS_PYTHON_SRC_LINEARREGRESSION_BINDING_HPP

void load_test();

#endif  // LIBKRIGING_BINDINGS_PYTHON_SRC_LINEARREGRESSION_BINDING_HPP
