"""scikit-learn compatible estimators wrapping libKriging's Python bindings.

This module is a thin adapter, not a reimplementation: every estimator
here simply constructs and delegates to the corresponding class in
``pylibkriging`` (``Kriging``, ...), while conforming to scikit-learn's
estimator API (``fit``/``predict``, ``get_params``/``set_params``,
cloning, ``Pipeline``/``GridSearchCV``/``cross_val_score`` compatibility).

The goal is substitutability: existing code written against
``sklearn.gaussian_process.GaussianProcessRegressor`` (or any other
sklearn regressor), including code generated by an AI assistant that
defaults to the sklearn API, should be able to swap in
``pylibkriging.sklearn.KrigingRegressor`` with no other changes.

This submodule requires scikit-learn, which is an *optional* dependency
of pylibkriging (see the ``sklearn`` extra in ``setup.py``) -- importing
``pylibkriging`` itself never requires it.
"""
from __future__ import annotations

import numpy as np

try:
    from sklearn.base import BaseEstimator, RegressorMixin
    from sklearn.utils.validation import check_array, check_is_fitted
    try:
        # sklearn >= 1.6
        from sklearn.utils.validation import validate_data
    except ImportError:
        validate_data = None
        from sklearn.utils.validation import check_X_y
except ImportError as exc:  # pragma: no cover - exercised via import error path
    raise ImportError(
        "pylibkriging.sklearn requires scikit-learn, which is not installed. "
        "Install it with 'pip install pylibkriging[sklearn]' or "
        "'pip install scikit-learn'."
    ) from exc

from . import Kriging as _Kriging

__all__ = ["KrigingRegressor"]


class KrigingRegressor(RegressorMixin, BaseEstimator):
    """Ordinary/universal Kriging as a scikit-learn-compatible regressor.

    A thin wrapper around :class:`pylibkriging.Kriging` that follows the
    scikit-learn estimator conventions, so libKriging can be dropped into
    existing sklearn code as a substitute for e.g.
    ``sklearn.gaussian_process.GaussianProcessRegressor`` -- inside a
    ``Pipeline``, ``GridSearchCV``, ``cross_val_score``, etc.

    See libKriging's ``skills/libkriging/SKILL.md`` (if present in your
    checkout) for guidance on which ``kernel``/``regmodel``/``objective``
    to pick for a given problem; this docstring only covers the sklearn
    surface.

    Parameters
    ----------
    kernel : {"matern5_2", "matern3_2", "gauss", "exp"}, default="matern5_2"
        Covariance kernel.
    regmodel : {"constant", "linear", "interactive", "quadratic", "none"}, default="constant"
        Trend / regression model.
    normalize : bool, default=False
        Rescale X/y to [0, 1] internally before fitting.
    optim : str, default="BFGS"
        Optimizer for the hyperparameters: ``"BFGS"``, ``"BFGS<k>"`` for
        k random restarts (e.g. ``"BFGS10"``), or ``"none"`` to keep
        `parameters` fixed rather than estimate them.
    objective : str, default="LL"
        Fit objective: ``"LL"``, ``"LOO"``, ``"LMP"``, ``"VLL"``, or
        ``"VLL(m)"`` (Vecchia approximation, for large ``n``).
    noise : None, "nugget", float, or array-like of shape (n_samples,), default=None
        ``None`` for noise-free (exact interpolation), ``"nugget"`` for
        an estimated homogeneous nugget, or a per-observation variance
        for known heteroskedastic noise.
    parameters : dict or None, default=None
        Optional starting/fixed hyperparameters
        (``sigma2``, ``theta``, ``beta``, plus ``is_*_estim`` flags),
        forwarded as-is to :class:`pylibkriging.Kriging`.

    Attributes
    ----------
    model_ : pylibkriging.Kriging
        The fitted libKriging model, set after calling ``fit``. Use this
        to reach libKriging-specific functionality that the sklearn API
        has no equivalent for: ``simulate``, ``update``,
        ``logLikelihood``, ``leaveOneOut``, ``save``/``load``, etc.
    n_features_in_ : int
        Number of input variables seen during ``fit``.

    Examples
    --------
    >>> import numpy as np
    >>> from pylibkriging.sklearn import KrigingRegressor
    >>> X = np.random.uniform(size=(20, 2))
    >>> y = np.sin(X[:, 0]) + np.cos(X[:, 1])
    >>> reg = KrigingRegressor(kernel="matern5_2").fit(X, y)
    >>> mean = reg.predict(X[:2])
    >>> mean, std = reg.predict(X[:2], return_std=True)

    Notes
    -----
    ``predict(X, return_std=True, return_cov=True)`` is not supported
    (mirroring ``GaussianProcessRegressor``, which raises for the same
    combination) -- request at most one of ``return_std``/``return_cov``.
    """

    def __init__(self, kernel="matern5_2", regmodel="constant", normalize=False,
                 optim="BFGS", objective="LL", noise=None, parameters=None):
        # sklearn convention: __init__ must only assign parameters to
        # identically-named attributes, with no validation or other
        # logic -- see scikit-learn's "Developing scikit-learn estimators"
        # guide. get_params()/set_params()/clone() rely on this.
        self.kernel = kernel
        self.regmodel = regmodel
        self.normalize = normalize
        self.optim = optim
        self.objective = objective
        self.noise = noise
        self.parameters = parameters

    def fit(self, X, y):
        """Fit a Kriging model to (X, y).

        Parameters
        ----------
        X : array-like of shape (n_samples, n_features)
        y : array-like of shape (n_samples,)

        Returns
        -------
        self
        """
        if validate_data is not None:
            X, y = validate_data(self, X, y, y_numeric=True, multi_output=False)
        else:  # sklearn < 1.6
            X, y = check_X_y(X, y, y_numeric=True, multi_output=False)
            self.n_features_in_ = X.shape[1]
        parameters = {} if self.parameters is None else dict(self.parameters)
        self.model_ = _Kriging(
            y, X, self.kernel,
            regmodel=self.regmodel,
            normalize=self.normalize,
            optim=self.optim,
            objective=self.objective,
            parameters=parameters,
            noise=self.noise,
        )
        return self

    def _validate_X_predict(self, X):
        if validate_data is not None:
            return validate_data(self, X, reset=False)
        check_array(X)
        if X.shape[1] != self.n_features_in_:
            raise ValueError(
                f"X has {X.shape[1]} features, but {type(self).__name__} "
                f"was fitted with {self.n_features_in_} features.")
        return X

    def predict(self, X, return_std=False, return_cov=False):
        """Predict at X.

        Parameters
        ----------
        X : array-like of shape (n_samples, n_features)
        return_std : bool, default=False
            Also return the predictive standard deviation.
        return_cov : bool, default=False
            Also return the full predictive covariance matrix.
            Mutually exclusive with `return_std`, matching
            ``GaussianProcessRegressor``.

        Returns
        -------
        mean : ndarray of shape (n_samples,)
        std : ndarray of shape (n_samples,), optional
            Only if `return_std` is True.
        cov : ndarray of shape (n_samples, n_samples), optional
            Only if `return_cov` is True.
        """
        if return_std and return_cov:
            raise RuntimeError(
                "At most one of return_std or return_cov can be requested.")
        check_is_fitted(self, "model_")
        X = self._validate_X_predict(X)
        # pylibkriging.Kriging.predict always returns a fixed 5-tuple
        # (mean, stdev, cov, mean_deriv, stdev_deriv); the return_stdev/
        # return_cov flags only control whether those entries are
        # actually computed, not how many are returned.
        mean, stdev, cov, _mean_deriv, _stdev_deriv = self.model_.predict(
            X, return_stdev=return_std, return_cov=return_cov, return_deriv=False)
        if return_cov:
            return mean, cov
        if return_std:
            return mean, stdev
        return mean

    def sample_y(self, X, n_samples=1, random_state=0):
        """Draw sample paths at X, conditional on the fitted data.

        Mirrors ``GaussianProcessRegressor.sample_y``'s signature.

        Parameters
        ----------
        X : array-like of shape (n_samples, n_features)
        n_samples : int, default=1
        random_state : int, default=0
            Forwarded as the simulation seed.

        Returns
        -------
        ndarray of shape (n_samples, n_samples_X)
        """
        check_is_fitted(self, "model_")
        X = self._validate_X_predict(X)
        seed = int(random_state) if random_state is not None else 123
        return self.model_.simulate(nsim=n_samples, seed=seed, X=X)

    # --- scikit-learn tag protocols (both are kept for compatibility
    # across the sklearn versions this might run under; each is only
    # ever invoked by the matching sklearn version) ---

    def _more_tags(self):
        # Pre-1.6 tag protocol.
        return {"requires_y": True, "poor_score": True}

    def __sklearn_tags__(self):
        # 1.6+ tag protocol.
        tags = super().__sklearn_tags__()
        tags.target_tags.required = True
        tags.regressor_tags.poor_score = True
        return tags
