"""scikit-learn compatible estimators wrapping libKriging's Python bindings.

This module is a thin adapter, not a reimplementation: every estimator
here simply constructs and delegates to the corresponding class in
``pylibkriging`` (``Kriging``, ...), while conforming to scikit-learn's
estimator API (``fit``/``predict``, ``get_params``/``set_params``,
cloning, ``Pipeline``/``GridSearchCV``/``cross_val_score`` compatibility).

The goal is substitutability: existing code written against
``sklearn.gaussian_process.GaussianProcessRegressor`` (or any other
sklearn regressor), including code generated by an AI assistant that
defaults to the sklearn API, should be able to swap in
``pylibkriging.sklearn.KrigingRegressor`` with no other changes.

This submodule requires scikit-learn, which is an *optional* dependency
of pylibkriging (see the ``sklearn`` extra in ``setup.py``) -- importing
``pylibkriging`` itself never requires it.
"""
from __future__ import annotations

import numpy as np

try:
    from sklearn.base import BaseEstimator, RegressorMixin
    from sklearn.utils.validation import check_array, check_is_fitted
    try:
        # sklearn >= 1.6
        from sklearn.utils.validation import validate_data
    except ImportError:
        validate_data = None
        from sklearn.utils.validation import check_X_y
except ImportError as exc:  # pragma: no cover - exercised via import error path
    raise ImportError(
        "pylibkriging.sklearn requires scikit-learn, which is not installed. "
        "Install it with 'pip install pylibkriging[sklearn]' or "
        "'pip install scikit-learn'."
    ) from exc

from . import Kriging as _Kriging
from . import MLPKriging as _MLPKriging
from . import NestedKriging as _NestedKriging
from . import WarpKriging as _WarpKriging

__all__ = [
    "KrigingRegressor",
    "WarpKrigingRegressor",
    "MLPKrigingRegressor",
    "NestedKrigingRegressor",
]


class _BaseKrigingEstimator(RegressorMixin, BaseEstimator):
    """Shared plumbing for every *Regressor class below: input validation
    consistent with `fit`'s `n_features_in_`, and both scikit-learn tag
    protocols. Not part of the public API -- subclasses provide their own
    `__init__`/`fit`/`predict` (sklearn's `get_params`/`set_params`
    introspect each concrete class's own `__init__` signature, so sharing
    that across a base class would be actively wrong, not just unnecessary)
    """

    def _validate_X_predict(self, X):
        if validate_data is not None:
            return validate_data(self, X, reset=False)
        check_array(X)
        if X.shape[1] != self.n_features_in_:
            raise ValueError(
                f"X has {X.shape[1]} features, but {type(self).__name__} "
                f"was fitted with {self.n_features_in_} features.")
        return X

    def _validate_X_fit_y(self, X, y):
        if validate_data is not None:
            return validate_data(self, X, y, y_numeric=True, multi_output=False)
        X, y = check_X_y(X, y, y_numeric=True, multi_output=False)
        self.n_features_in_ = X.shape[1]
        return X, y

    def _more_tags(self):
        # Pre-1.6 tag protocol.
        return {"requires_y": True, "poor_score": True}

    def __sklearn_tags__(self):
        # 1.6+ tag protocol.
        tags = super().__sklearn_tags__()
        tags.target_tags.required = True
        tags.regressor_tags.poor_score = True
        return tags


class KrigingRegressor(_BaseKrigingEstimator):
    """Ordinary/universal Kriging as a scikit-learn-compatible regressor.

    A thin wrapper around :class:`pylibkriging.Kriging` that follows the
    scikit-learn estimator conventions, so libKriging can be dropped into
    existing sklearn code as a substitute for e.g.
    ``sklearn.gaussian_process.GaussianProcessRegressor`` -- inside a
    ``Pipeline``, ``GridSearchCV``, ``cross_val_score``, etc.

    See libKriging's ``skills/libkriging/SKILL.md`` (if present in your
    checkout) for guidance on which ``kernel``/``regmodel``/``objective``
    to pick for a given problem; this docstring only covers the sklearn
    surface.

    Parameters
    ----------
    kernel : {"matern5_2", "matern3_2", "gauss", "exp"}, default="matern5_2"
        Covariance kernel.
    regmodel : {"constant", "linear", "interactive", "quadratic", "none"}, default="constant"
        Trend / regression model.
    normalize : bool, default=False
        Rescale X/y to [0, 1] internally before fitting.
    optim : str, default="BFGS"
        Optimizer for the hyperparameters: ``"BFGS"``, ``"BFGS<k>"`` for
        k random restarts (e.g. ``"BFGS10"``), or ``"none"`` to keep
        `parameters` fixed rather than estimate them.
    objective : str, default="LL"
        Fit objective: ``"LL"``, ``"LOO"``, ``"LMP"``, ``"VLL"``, or
        ``"VLL(m)"`` (Vecchia approximation, for large ``n``).
    noise : None, "nugget", float, or array-like of shape (n_samples,), default=None
        ``None`` for noise-free (exact interpolation), ``"nugget"`` for
        an estimated homogeneous nugget, or a per-observation variance
        for known heteroskedastic noise.
    parameters : dict or None, default=None
        Optional starting/fixed hyperparameters
        (``sigma2``, ``theta``, ``beta``, plus ``is_*_estim`` flags),
        forwarded as-is to :class:`pylibkriging.Kriging`.

    Attributes
    ----------
    model_ : pylibkriging.Kriging
        The fitted libKriging model, set after calling ``fit``. Use this
        to reach libKriging-specific functionality that the sklearn API
        has no equivalent for: ``simulate``, ``update``,
        ``logLikelihood``, ``leaveOneOut``, ``save``/``load``, etc.
    n_features_in_ : int
        Number of input variables seen during ``fit``.

    Examples
    --------
    >>> import numpy as np
    >>> from pylibkriging.sklearn import KrigingRegressor
    >>> X = np.random.uniform(size=(20, 2))
    >>> y = np.sin(X[:, 0]) + np.cos(X[:, 1])
    >>> reg = KrigingRegressor(kernel="matern5_2").fit(X, y)
    >>> mean = reg.predict(X[:2])
    >>> mean, std = reg.predict(X[:2], return_std=True)

    Notes
    -----
    ``predict(X, return_std=True, return_cov=True)`` is not supported
    (mirroring ``GaussianProcessRegressor``, which raises for the same
    combination) -- request at most one of ``return_std``/``return_cov``.
    """

    def __init__(self, kernel="matern5_2", regmodel="constant", normalize=False,
                 optim="BFGS", objective="LL", noise=None, parameters=None):
        # sklearn convention: __init__ must only assign parameters to
        # identically-named attributes, with no validation or other
        # logic -- see scikit-learn's "Developing scikit-learn estimators"
        # guide. get_params()/set_params()/clone() rely on this.
        self.kernel = kernel
        self.regmodel = regmodel
        self.normalize = normalize
        self.optim = optim
        self.objective = objective
        self.noise = noise
        self.parameters = parameters

    def fit(self, X, y):
        """Fit a Kriging model to (X, y).

        Parameters
        ----------
        X : array-like of shape (n_samples, n_features)
        y : array-like of shape (n_samples,)

        Returns
        -------
        self
        """
        X, y = self._validate_X_fit_y(X, y)
        parameters = {} if self.parameters is None else dict(self.parameters)
        self.model_ = _Kriging(
            y, X, self.kernel,
            regmodel=self.regmodel,
            normalize=self.normalize,
            optim=self.optim,
            objective=self.objective,
            parameters=parameters,
            noise=self.noise,
        )
        return self

    def predict(self, X, return_std=False, return_cov=False):
        """Predict at X.

        Parameters
        ----------
        X : array-like of shape (n_samples, n_features)
        return_std : bool, default=False
            Also return the predictive standard deviation.
        return_cov : bool, default=False
            Also return the full predictive covariance matrix.
            Mutually exclusive with `return_std`, matching
            ``GaussianProcessRegressor``.

        Returns
        -------
        mean : ndarray of shape (n_samples,)
        std : ndarray of shape (n_samples,), optional
            Only if `return_std` is True.
        cov : ndarray of shape (n_samples, n_samples), optional
            Only if `return_cov` is True.
        """
        if return_std and return_cov:
            raise RuntimeError(
                "At most one of return_std or return_cov can be requested.")
        check_is_fitted(self, "model_")
        X = self._validate_X_predict(X)
        # pylibkriging.Kriging.predict always returns a fixed 5-tuple
        # (mean, stdev, cov, mean_deriv, stdev_deriv); the return_stdev/
        # return_cov flags only control whether those entries are
        # actually computed, not how many are returned.
        mean, stdev, cov, _mean_deriv, _stdev_deriv = self.model_.predict(
            X, return_stdev=return_std, return_cov=return_cov, return_deriv=False)
        if return_cov:
            return mean, cov
        if return_std:
            return mean, stdev
        return mean

    def sample_y(self, X, n_samples=1, random_state=0):
        """Draw sample paths at X, conditional on the fitted data.

        Mirrors ``GaussianProcessRegressor.sample_y``'s signature.

        Parameters
        ----------
        X : array-like of shape (n_samples, n_features)
        n_samples : int, default=1
        random_state : int, default=0
            Forwarded as the simulation seed.

        Returns
        -------
        ndarray of shape (n_samples, n_samples_X)
        """
        check_is_fitted(self, "model_")
        X = self._validate_X_predict(X)
        seed = int(random_state) if random_state is not None else 123
        return self.model_.simulate(nsim=n_samples, seed=seed, X=X)


class WarpKrigingRegressor(_BaseKrigingEstimator):
    """WarpKriging as a scikit-learn-compatible regressor: per-variable
    input warping for mixed continuous / categorical / ordinal inputs.

    A thin wrapper around :class:`pylibkriging.WarpKriging`. See
    ``skills/libkriging/SKILL.md`` (if present in your checkout), section
    4, for the warp-spec vocabulary (``"affine"``, ``"boxcox"``,
    ``"kumaraswamy"``, ``"neural_mono(H)"``, ``"categorical(L,q)"``,
    ``"ordinal(L)"``, ``"none"``).

    Parameters
    ----------
    warping : list of str, or None, default=None
        One spec string per column of `X`, in column order. ``None``
        (the default, needed so this estimator is constructible with no
        arguments -- see scikit-learn's estimator conventions) means
        ``["none"] * n_features`` at `fit` time, i.e. no warp at all --
        equivalent to plain `KrigingRegressor`, so there's no reason to
        leave this at its default in practice. Its length must match
        `X`'s number of columns at `fit` time.
    kernel : str, default="gauss"
    regmodel : str, default="constant"
    normalize : bool, default=False
    optim : str, default="BFGS+Adam"
        Note this default differs from `KrigingRegressor`'s `"BFGS"`:
        fitting the warp parameters benefits from the extra Adam-style
        steps, matching libKriging's own default for this class.
    objective : str, default="LL"
    noise : None, "nugget", float, or array-like, default=None
    parameters : dict or None, default=None

    Attributes
    ----------
    model_ : pylibkriging.WarpKriging
    n_features_in_ : int
    warping_ : list of str
        The warp spec actually used to fit (post `None`-resolution).

    Notes
    -----
    ``predict(X, return_std=True, return_cov=True)`` is not supported,
    same restriction as `KrigingRegressor`.
    """

    def __init__(self, warping=None, kernel="gauss", regmodel="constant",
                 normalize=False, optim="BFGS+Adam", objective="LL",
                 noise=None, parameters=None):
        self.warping = warping
        self.kernel = kernel
        self.regmodel = regmodel
        self.normalize = normalize
        self.optim = optim
        self.objective = objective
        self.noise = noise
        self.parameters = parameters

    def fit(self, X, y):
        X, y = self._validate_X_fit_y(X, y)
        self.warping_ = (list(self.warping) if self.warping is not None
                          else ["none"] * X.shape[1])
        if len(self.warping_) != X.shape[1]:
            raise ValueError(
                f"warping has {len(self.warping_)} entries but X has "
                f"{X.shape[1]} columns; one warp spec per column is required.")
        parameters = {} if self.parameters is None else dict(self.parameters)
        self.model_ = _WarpKriging(
            y, X, self.warping_,
            kernel=self.kernel,
            regmodel=self.regmodel,
            normalize=self.normalize,
            optim=self.optim,
            objective=self.objective,
            parameters=parameters,
            noise=self.noise,
        )
        return self

    def predict(self, X, return_std=False, return_cov=False):
        if return_std and return_cov:
            raise RuntimeError(
                "At most one of return_std or return_cov can be requested.")
        check_is_fitted(self, "model_")
        X = self._validate_X_predict(X)
        mean, stdev, cov, _md, _sd = self.model_.predict(
            X, return_stdev=return_std, return_cov=return_cov, return_deriv=False)
        if return_cov:
            return mean, cov
        if return_std:
            return mean, stdev
        return mean

    def sample_y(self, X, n_samples=1, random_state=0):
        check_is_fitted(self, "model_")
        X = self._validate_X_predict(X)
        seed = int(random_state) if random_state is not None else 123
        return self.model_.simulate(nsim=n_samples, seed=seed, X=X)


class MLPKrigingRegressor(_BaseKrigingEstimator):
    """MLPKriging as a scikit-learn-compatible regressor: a joint MLP
    feature map shared across all inputs (deep-kernel learning), as
    opposed to `WarpKrigingRegressor`'s one-warp-per-variable.

    A thin wrapper around :class:`pylibkriging.MLPKriging`.

    Parameters
    ----------
    hidden_dims : sequence of int, default=(8,)
        MLP hidden layer widths. libKriging's own binding has no default
        for this (it's a required argument in the C++/pybind signature);
        `(8,)` is a small, safe starting point chosen here only so this
        estimator is constructible with no arguments -- tune it for your
        problem.
    d_out : int, default=2
        Output (feature-map) dimension fed to the GP kernel.
    activation : str, default="selu"
    kernel : str, default="gauss"
    regmodel : str, default="constant"
    normalize : bool, default=False
    optim : str, default="BFGS+Adam"
    objective : str, default="LL"
    parameters : dict or None, default=None

    Attributes
    ----------
    model_ : pylibkriging.MLPKriging
    n_features_in_ : int

    Notes
    -----
    No `noise` parameter: libKriging's `MLPKriging` binding doesn't
    expose one (as of the version this was written against). Same
    `return_std`/`return_cov` mutual-exclusivity restriction as
    `KrigingRegressor`.
    """

    def __init__(self, hidden_dims=(8,), d_out=2, activation="selu",
                 kernel="gauss", regmodel="constant", normalize=False,
                 optim="BFGS+Adam", objective="LL", parameters=None):
        self.hidden_dims = hidden_dims
        self.d_out = d_out
        self.activation = activation
        self.kernel = kernel
        self.regmodel = regmodel
        self.normalize = normalize
        self.optim = optim
        self.objective = objective
        self.parameters = parameters

    def fit(self, X, y):
        X, y = self._validate_X_fit_y(X, y)
        parameters = {} if self.parameters is None else dict(self.parameters)
        self.model_ = _MLPKriging(
            y, X, list(self.hidden_dims), self.d_out,
            activation=self.activation,
            kernel=self.kernel,
            regmodel=self.regmodel,
            normalize=self.normalize,
            optim=self.optim,
            objective=self.objective,
            parameters=parameters,
        )
        return self

    def predict(self, X, return_std=False, return_cov=False):
        if return_std and return_cov:
            raise RuntimeError(
                "At most one of return_std or return_cov can be requested.")
        check_is_fitted(self, "model_")
        X = self._validate_X_predict(X)
        mean, stdev, cov, _md, _sd = self.model_.predict(
            X, return_stdev=return_std, return_cov=return_cov, return_deriv=False)
        if return_cov:
            return mean, cov
        if return_std:
            return mean, stdev
        return mean

    def sample_y(self, X, n_samples=1, random_state=0):
        check_is_fitted(self, "model_")
        X = self._validate_X_predict(X)
        seed = int(random_state) if random_state is not None else 123
        return self.model_.simulate(nsim=n_samples, seed=seed, X=X)


class NestedKrigingRegressor(_BaseKrigingEstimator):
    """NestedKriging as a scikit-learn-compatible regressor:
    divide-and-conquer kriging for large designs.

    A thin wrapper around :class:`pylibkriging.NestedKriging`. See
    ``skills/libkriging/SKILL.md`` (if present in your checkout), section
    3, for the aggregation trade-off.

    Parameters
    ----------
    kernel : str, default="matern5_2"
    nb_groups : int, default=10
        Number of groups the design is partitioned into. libKriging's own
        binding has no default for this (required in the C++/pybind
        signature); `10` is a placeholder chosen only so this estimator
        is constructible with no arguments. Tune relative to your design
        size -- `NestedKriging` targets large n; for the design sizes
        typical of a quick example or a unit test, plain
        `KrigingRegressor` is simpler and just as good.
    aggregation : {"NK", "PoE", "gPoE", "BCM", "rBCM"}, default="NK"
        "NK" is the only aggregation that's a proper (interpolating,
        variance-consistent) kriging predictor, and it *requires*
        `regmodel="constant"` (simple-kriging theory) -- `fit` raises if
        you combine "NK" with another `regmodel`.
    partition : {"kmeans", "random"}, default="kmeans"
    seed : int, default=123
    regmodel : str, default="constant"
    optim : str, default="BFGS"
    objective : str, default="LL"
    parameters : dict or None, default=None
    warping : list of str or None, default=None
        Non-``None`` switches the per-group submodels to `WarpKriging`
        instead of plain `Kriging`.

    Attributes
    ----------
    model_ : pylibkriging.NestedKriging
    n_features_in_ : int

    Notes
    -----
    - No `noise`/`normalize` parameters: libKriging's `NestedKriging`
      binding doesn't expose them (as of the version this was written
      against).
    - `predict` only supports `return_std`, not `return_cov` -- the
      underlying binding's `predict` doesn't compute a covariance matrix
      at all (2-tuple return, unlike the other three classes' 5-tuple).
    - No `sample_y`: `NestedKriging` doesn't expose `simulate`.
    """

    def __init__(self, kernel="matern5_2", nb_groups=10, aggregation="NK",
                 partition="kmeans", seed=123, regmodel="constant",
                 optim="BFGS", objective="LL", parameters=None, warping=None):
        self.kernel = kernel
        self.nb_groups = nb_groups
        self.aggregation = aggregation
        self.partition = partition
        self.seed = seed
        self.regmodel = regmodel
        self.optim = optim
        self.objective = objective
        self.parameters = parameters
        self.warping = warping

    def fit(self, X, y):
        X, y = self._validate_X_fit_y(X, y)
        if self.aggregation == "NK" and self.regmodel != "constant":
            raise ValueError(
                "aggregation='NK' requires regmodel='constant' (simple-kriging "
                f"theory); got regmodel={self.regmodel!r}. Either set "
                "regmodel='constant' or pick a different aggregation "
                "('PoE'/'gPoE'/'BCM'/'rBCM').")
        parameters = {} if self.parameters is None else dict(self.parameters)
        warping = [] if self.warping is None else list(self.warping)
        self.model_ = _NestedKriging(
            y, X, self.kernel, self.nb_groups,
            aggregation=self.aggregation,
            partition=self.partition,
            seed=self.seed,
            regmodel=self.regmodel,
            optim=self.optim,
            objective=self.objective,
            parameters=parameters,
            warping=warping,
        )
        return self

    def predict(self, X, return_std=False):
        check_is_fitted(self, "model_")
        X = self._validate_X_predict(X)
        mean, stdev = self.model_.predict(X, return_stdev=return_std)
        if return_std:
            return mean, stdev
        return mean
