# VERSION must follow pattern : <major>.<minor>.<patch>
set(KRIGING_VERSION_MAJOR v0)
set(KRIGING_VERSION_MINOR 5)
set(KRIGING_VERSION_PATCH 0)
set(KRIGING_VERSION "${KRIGING_VERSION_MAJOR}.${KRIGING_VERSION_MINOR}.${KRIGING_VERSION_PATCH}")
